name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            kill -9 `cat save_pid.txt`
            rm -rf prod
            mkdir -p prod
            cd prod
            git clone https://github.com/antoniogamiz/inversor.git .
            nohup deno run --allow-net --allow-env server.ts > ../my.log &
            echo $! > ../save_pid.txt
            echo "Deployment successful!"
